apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gymio
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "gymio"
    ingress.gcp.kubernetes.io/pre-shared-cert: "gymio-api"
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: gymio
    servicePort: 8080